server:
  port: 12002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12001/eureka/
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: spring-cloud-product
          uri: lb://spring-cloud-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

        - id: spring-cloud-payment
          uri: lb://spring-cloud-payment
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
