server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://192.168.31.50:27017
      database: education
  rabbitmq:
    host: 192.168.31.50
    port: 5672
    username: root
    password: 123456
    virtual-host: /
xuecheng:
  mq:
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1
