
server:
  port: 12003
spring:
  application:
    name: spring-cloud-product
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://192.168.31.50:3306/xc_course?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12001/eureka/
my:
  car:
    name: 比亚迪
    price: 1200000
feign:
  httpclient:
    connection-timeout: 10000
