server:
  port: 12004
spring:
  application:
    name: spring-cloud-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.50:3306/xc_course?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.cloud.entities
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12001/eureka/
  instance:
    instance-id: payment12004
    ip-address: true